### PR TITLE
Hard coded 60s pause every 2 requests

### PR DESCRIPTION
**Pull request by gerwaric**
Since the dynamic approach to rate-limiting based on the HTTP headers is buggy, here's a simpler approach that uses the prior framework to hard-code a 60 pause after every 2 requests. This should keep Acquisition under the most restrictive of GGG's current policies, which I think is 100 requests per 1800 seconds.

### CODE REVIEW

**Comment by Akymo** [comment]
is this updated with latest version ?

**Comment by gerwaric** [comment]
> is this updated with latest version ?

No, I think the latest current release is still broken, so you’d need to go back to an earlier one.

I was never able to replicate the errors other people had with the new way of handling rate limits, unfortunately, and I’m also going to be offline for burning man for the next couple weeks, so this might not be fixed for a bit.

I can check back in September to so where things are at and maybe take  second crack at trying to improve the rate limiting.

**Comment by Akymo** [comment]
is there any version at all that works now? or how i can get it to work?

**Comment by gerwaric** [comment]
I don't think there is, sorry. At this point, I need someone to help me debug the problem with the rate-limiting approach I coded a couple weeks ago. It works great for me, but I believe it's still broken for everyone else who has tried it, and I've been unable to replicate those errors.

**Comment by Akymo** [comment]
add me on discord Azuwi ill help you debug it

**Comment by gerwaric** [comment]
Thank you, that would be fantastic. Look for a friend request; my discord username begins with a g, and I just sent one.

**Comment by gerwaric** [comment]
I'm back at work on my original dynamic rate limiting. My first implementation broke for people outside the US where their computer was set to a non-English language. This time someone from the EU who experienced that bug is helping me, and we have already gotten past that first bug. I'm going to close this pull request now.

**Pull request closed without merging**
